import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  pickQuizBlock: {
    backgroundColor: "#fff",
    width: 28,
    height: 28,
    borderColor: "#fff",
  },
  unPickBlock: {
    width: 24,
    height: 24,
    backgroundColor: "#C6B1FF",
    borderWidth: 1,
    borderColor: "#93B8FE",
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
  },

  textUnpick: {
    textAlign: "left",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 28,
    color: "#1E1E1E",
    width: 280,
  },
  container: {
    width: "100%",
    height: "auto",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 16,
    shadowOpacity: 0.6,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 8,
    shadowColor: "rgba(0, 0, 0, 0.12)",
    padding: 12,
    backgroundColor: "#fff",
  },
  containerQuizPage: {
    alignSelf: "center",
    marginTop: 14,
    width: "100%",
    paddingHorizontal: 16,
  },
  textProgress: {
    alignSelf: "center",
    color: "#000000",
    fontWeight: "600",
    fontSize: 17,
    lineHeight: 22,
    textAlign: "center",
    marginBottom: 18,
  },
  titleText: {
    alignSelf: "flex-start",
    color: "#000000",
    fontWeight: "700",
    fontSize: 24,
    lineHeight: 28,
    textAlign: "left",
    marginBottom: 18,
    marginTop: 40,
    marginHorizontal: 16,
  },
  buttonView: {
    position: "absolute",
    width: "100%",
    paddingHorizontal: 16,
    bottom: 30,
  },
});
